# -*- coding: utf-8 -*-
"""Project Plan CC26-PSU038.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CTHJ4da-bWn3X9fFkQ2je5JXYGh_lDA

**Pertanyaan Bisnis**

1. Bagaimana membangun model NLP yang mampu mengklasifikasikan berita hoax dan valid pada dataset berita Indonesia periode 2024–2025 dengan tingkat akurasi yang baik?
2. Kata, frasa, atau pola teks apa yang paling sering muncul pada berita hoax dibandingkan berita valid berdasarkan hasil analisis dataset berita Indonesia?
3. Bagaimana sistem klasifikasi berita hoax berbasis web dapat membantu pengguna melakukan verifikasi informasi secara lebih cepat selama proses pengujian aplikasi?
"""

import pandas as pd
import numpy as np
import re
import string

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

"""DATA GATHERING"""

# load dataset
df = pd.read_csv("dataset_final.csv")

# menampilkan 5 data pertama
df.head()

"""**ASSESING DATA**"""

# melihat ukuran dataset
print("Ukuran Dataset:")
print(df.shape)

# melihat informasi dataset
print("\nInfo Dataset:")
print(df.info())

print("Missing Value:")
print(df.isnull().sum())

duplicate = df.duplicated().sum()

print("Jumlah Data Duplikat:", duplicate)

"""**CLEANING DATA**"""

# menghapus missing value
df = df.dropna()

# menghapus data duplikat
df = df.drop_duplicates()

print("Ukuran dataset setelah cleaning:")
print(df.shape)

print(df["label"].value_counts())

sns.countplot(x=df["label"])

plt.title("Distribusi Label Berita")
plt.xlabel("Label")
plt.ylabel("Jumlah")

plt.show()

stop_words = set(stopwords.words('indonesian'))

print(list(stop_words)[:20])

def clean_text(text):

    # lowercase
    text = text.lower()

    # menghapus URL
    text = re.sub(r"http\S+", "", text)

    # menghapus mention dan hashtag
    text = re.sub(r"@\w+|#\w+", "", text)

    # menghapus angka
    text = re.sub(r"\d+", "", text)

    # menghapus tanda baca
    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )

    # menghapus spasi berlebih
    text = re.sub(r"\s+", " ", text).strip()

    # tokenisasi
    words = text.split()

    # menghapus stopword
    filtered_words = [
        word for word in words
        if word not in stop_words
    ]

    # gabungkan kembali
    text = " ".join(filtered_words)

    return text

df["clean_text"] = df["text"].apply(clean_text)

df[["text", "clean_text"]].head()

"""**EXPLORATORY DATA ANALYSIS**"""

print(df["label"].value_counts())

sns.countplot(x=df["label"])

plt.title("Distribusi Label Berita")
plt.xlabel("Label")
plt.ylabel("Jumlah")

plt.show()

df["jumlah_karakter"] = df["clean_text"].apply(len)

df["jumlah_karakter"].describe()

plt.figure(figsize=(10,5))

sns.histplot(df["jumlah_karakter"], bins=50)

plt.title("Distribusi Jumlah Karakter")
plt.xlabel("Jumlah Karakter")
plt.ylabel("Frekuensi")

plt.show()

df["jumlah_kata"] = df["clean_text"].apply(
    lambda x: len(str(x).split())
)

df["jumlah_kata"].describe()

plt.figure(figsize=(10,5))

sns.histplot(df["jumlah_kata"], bins=50)

plt.title("Distribusi Jumlah Kata")
plt.xlabel("Jumlah Kata")
plt.ylabel("Frekuensi")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    x="label",
    y="jumlah_kata",
    data=df
)

plt.title("Perbandingan Jumlah Kata Berdasarkan Label")
plt.xlabel("Label")
plt.ylabel("Jumlah Kata")

plt.show()

from collections import Counter

all_text = " ".join(df["clean_text"])

words = all_text.split()

counter = Counter(words)

common_words = counter.most_common(20)

common_df = pd.DataFrame(
    common_words,
    columns=["Kata", "Frekuensi"]
)

common_df

plt.figure(figsize=(12,6))

sns.barplot(
    x="Frekuensi",
    y="Kata",
    data=common_df
)

plt.title("20 Kata yang Paling Sering Muncul")

plt.show()

hoax_text = " ".join(
    df[df["label"] == 1]["clean_text"]
)

hoax_words = hoax_text.split()

hoax_counter = Counter(hoax_words)

hoax_common = hoax_counter.most_common(20)

hoax_df = pd.DataFrame(
    hoax_common,
    columns=["Kata", "Frekuensi"]
)

hoax_df

plt.figure(figsize=(12,6))

sns.barplot(
    x="Frekuensi",
    y="Kata",
    data=hoax_df
)

plt.title("20 Kata pada Berita Hoax")

plt.show()

valid_text = " ".join(
    df[df["label"] == 0]["clean_text"]
)

valid_words = valid_text.split()

valid_counter = Counter(valid_words)

valid_common = valid_counter.most_common(20)

valid_df = pd.DataFrame(
    valid_common,
    columns=["Kata", "Frekuensi"]
)

valid_df

plt.figure(figsize=(12,6))

sns.barplot(
    x="Frekuensi",
    y="Kata",
    data=valid_df
)

plt.title("20 Kata pada Berita Valid")

plt.show()

from wordcloud import WordCloud

wordcloud = WordCloud(
    width=800,
    height=400,
    background_color='white'
).generate(all_text)

plt.figure(figsize=(15,7))

plt.imshow(wordcloud, interpolation='bilinear')

plt.axis("off")

plt.title("WordCloud Seluruh Berita")

plt.show()

wordcloud_hoax = WordCloud(
    width=800,
    height=400,
    background_color='white'
).generate(hoax_text)

plt.figure(figsize=(15,7))

plt.imshow(wordcloud_hoax, interpolation='bilinear')

plt.axis("off")

plt.title("WordCloud Berita Hoax")

plt.show()

wordcloud_valid = WordCloud(
    width=800,
    height=400,
    background_color='white'
).generate(valid_text)

plt.figure(figsize=(15,7))

plt.imshow(wordcloud_valid, interpolation='bilinear')

plt.axis("off")

plt.title("WordCloud Berita Valid")

plt.show()

"""VISUALISASI

1. Bagaimana membangun model NLP yang mampu mengklasifikasikan berita hoax dan valid pada dataset berita Indonesia periode 2024–2025 dengan tingkat akurasi yang baik?
"""

sns.set_style("whitegrid")

plt.figure(figsize=(8,5))

ax = sns.countplot(
    x='label',
    data=df,
    palette=['#d62828', '#003049']
)

plt.title(
    'Distribusi Berita Hoax dan Valid\nDataset Berita Indonesia 2024–2025',
    fontsize=15,
    fontweight='bold',
    pad=20
)

plt.xlabel('Kategori Berita', fontsize=12)
plt.ylabel('Jumlah Data', fontsize=12)

# Label jumlah data
for p in ax.patches:
    ax.annotate(
        f'{int(p.get_height())}',
        (p.get_x() + p.get_width()/2, p.get_height()),
        ha='center',
        va='bottom',
        fontsize=11,
        fontweight='bold'
    )

# jarak layout
plt.tight_layout(pad=3)

plt.show()


print("\n")
print("="*80)
print("\n")

#2

df['panjang_teks'] = df['clean_text'].astype(str).apply(len)

plt.figure(figsize=(10,5))

sns.histplot(
    df['panjang_teks'],
    bins=40,
    kde=True,
    color='#005f73'
)

plt.title(
    'Distribusi Panjang Teks Berita Indonesia',
    fontsize=15,
    fontweight='bold',
    pad=20
)

plt.xlabel('Jumlah Karakter', fontsize=12)
plt.ylabel('Frekuensi', fontsize=12)

# Memberi jarak layout
plt.tight_layout(pad=3)

plt.show()

"""Analisis Grafik Distribusi Berita Hoax dan Valid

1. Berdasarkan grafik di atas, jumlah berita hoax lebih banyak dibandingkan berita valid. Kategori hoax memiliki 38.107 data, sedangkan berita valid berjumlah 27.627 data.

2. Perbedaan jumlah data menunjukkan bahwa dataset belum seimbang karena kategori hoax menjadi kelas mayoritas. Kondisi ini dapat memengaruhi proses pelatihan model machine learning.

3. Ketidakseimbangan data dapat menyebabkan model lebih mudah mengenali pola berita hoax dibandingkan berita valid. Oleh karena itu, diperlukan perhatian pada proses modeling agar hasil klasifikasi tetap optimal.

2. Kata, frasa, atau pola teks apa yang paling sering muncul pada berita hoax dibandingkan berita valid berdasarkan hasil analisis dataset berita Indonesia?
"""

# mengambil teks berita hoax
hoax_text = ' '.join(
    df[df['label'] == 1]['clean_text']
    .dropna()
    .astype(str)
)

# menghitung frekuensi kata
hoax_words = hoax_text.split()

hoax_freq = Counter(hoax_words)

# mengambil 10 kata teratas
top_hoax = pd.DataFrame(
    hoax_freq.most_common(10),
    columns=['Kata', 'Frekuensi']
)

# visualisasi
plt.figure(figsize=(11,6))

ax = sns.barplot(
    x='Frekuensi',
    y='Kata',
    data=top_hoax,
    palette='Reds_r'
)

plt.title(
    '10 Kata yang Paling Sering Muncul pada Berita Hoax',
    fontsize=17,
    fontweight='bold',
    pad=20
)

plt.xlabel('Frekuensi', fontsize=12)
plt.ylabel('Kata', fontsize=12)

# menampilkan angka frekuensi
for i in ax.containers:
    ax.bar_label(i, padding=5, fontsize=10)

plt.tight_layout(pad=3)

plt.show()

"""Analisis :
1. Berdasarkan grafik di atas, kata yang paling sering muncul pada berita hoax adalah “video”, “akun”, dan “beredar”. Hal ini menunjukkan bahwa banyak berita hoax dalam dataset disebarkan melalui media sosial dalam bentuk video atau unggahan akun tertentu.

2. Kata seperti “facebook”, “media”, dan “sosial” juga memiliki frekuensi yang cukup tinggi. Dari hasil tersebut dapat diketahui bahwa penyebaran berita hoax banyak berkaitan dengan platform media sosial dan informasi yang beredar di internet.

3. Kemunculan kata “narasi”, “informasi”, dan “foto” menunjukkan bahwa berita hoax sering menggunakan narasi tertentu serta gambar atau video untuk menarik perhatian pembaca. Kata-kata yang sering muncul ini dapat membantu model machine learning dalam mengenali pola pada berita hoax.
"""

# mengambil teks berita fakta
valid_text = ' '.join(
    df[df['label'] == 0]['clean_text']
    .dropna()
    .astype(str)
)

# memecah kata
valid_words = valid_text.split()

# menghitung frekuensi kata
valid_freq = Counter(valid_words)

# mengambil 10 kata teratas
top_valid = pd.DataFrame(
    valid_freq.most_common(10),
    columns=['Kata', 'Frekuensi']
)

# visualisasi
plt.figure(figsize=(11,6))

ax = sns.barplot(
    x='Frekuensi',
    y='Kata',
    data=top_valid,
    palette='Blues_r'
)

plt.title(
    '10 Kata yang Paling Sering Muncul pada Berita Fakta',
    fontsize=17,
    fontweight='bold',
    pad=20
)

plt.xlabel('Frekuensi', fontsize=12)
plt.ylabel('Kata', fontsize=12)

# menampilkan angka
for i in ax.containers:
    ax.bar_label(i, padding=5, fontsize=10)

plt.tight_layout(pad=3)

plt.show()

"""Analisis :

1. Berdasarkan grafik di atas, kata yang paling sering muncul pada berita fakta adalah “partai”, “politik”, dan “jakarta”. Hal ini menunjukkan bahwa sebagian besar berita fakta dalam dataset membahas topik politik dan pemerintahan di Indonesia.

2. Kata seperti “presiden”, “pemilu”, “pemerintah”, dan “jokowi” juga memiliki frekuensi yang cukup tinggi. Dari hasil tersebut dapat diketahui bahwa berita fakta banyak berisi informasi mengenai kegiatan pemerintahan, pemilu, dan tokoh politik nasional.

3. Frekuensi kemunculan kata yang berhubungan dengan politik menunjukkan bahwa dataset berita fakta didominasi oleh berita bertema politik. Kata-kata yang sering muncul ini nantinya dapat membantu model machine learning dalam mengenali pola pada berita fakta.

3. Bagaimana sistem klasifikasi berita hoax berbasis web dapat membantu pengguna melakukan verifikasi informasi secara lebih cepat selama proses pengujian aplikasi?
"""

sns.set_style("whitegrid")

# menghitung jumlah prediksi tiap kategori
hasil_prediksi = df['label'].value_counts()

# mengubah label angka menjadi teks
kategori = ['Fakta', 'Hoax']
jumlah = [
    hasil_prediksi.get(0, 0),
    hasil_prediksi.get(1, 0)
]

# membuat dataframe
prediksi_df = pd.DataFrame({
    'Kategori': kategori,
    'Jumlah': jumlah
})

# visualisasi
plt.figure(figsize=(8,5))

ax = sns.barplot(
    x='Kategori',
    y='Jumlah',
    data=prediksi_df,
    palette=['#1d3557', '#d62828']
)

plt.title(
    'Distribusi Hasil Klasifikasi Sistem',
    fontsize=17,
    fontweight='bold',
    pad=20
)

plt.xlabel('Kategori Berita', fontsize=12)
plt.ylabel('Jumlah Data', fontsize=12)

# menampilkan jumlah pada bar
for i in ax.containers:
    ax.bar_label(i, padding=5, fontsize=10)

plt.tight_layout(pad=3)

plt.show()

"""Analisis :
1. Berdasarkan grafik, jumlah berita Hoax lebih banyak dibandingkan berita Fakta. Data Hoax berjumlah 38.107, sedangkan data Fakta berjumlah 27.627.

2. Perbedaan jumlah data menunjukkan bahwa distribusi dataset belum seimbang karena kategori Hoax menjadi kelas mayoritas.

3. Ketidakseimbangan data dapat memengaruhi performa model klasifikasi karena model cenderung lebih mudah mengenali pola pada kelas yang jumlah datanya lebih banyak.
"""

# menghitung persentase
persentase = prediksi_df['Jumlah'] / prediksi_df['Jumlah'].sum() * 100

plt.figure(figsize=(7,7))

plt.pie(
    persentase,
    labels=prediksi_df['Kategori'],
    autopct='%1.1f%%',
    startangle=90,
    colors=['#457b9d', '#e63946'],
    textprops={'fontsize': 12}
)

plt.title(
    'Persentase Klasifikasi Berita oleh Sistem',
    fontsize=17,
    fontweight='bold',
    pad=20
)

plt.tight_layout()

plt.show()

"""Analisis :

1. Berdasarkan diagram lingkaran di atas, hasil klasifikasi sistem menunjukkan bahwa berita Hoax memiliki persentase lebih besar dibandingkan berita Fakta. Kategori Hoax memperoleh persentase sebesar 58%, sedangkan Fakta sebesar 42%.

2. Perbedaan persentase tersebut menunjukkan bahwa jumlah berita hoax dalam dataset masih mendominasi dibandingkan berita fakta. Hal ini sejalan dengan distribusi data sebelumnya yang menunjukkan kelas hoax lebih banyak.

3. Distribusi persentase ini dapat memengaruhi proses klasifikasi karena model cenderung lebih sering mempelajari pola pada berita hoax dibandingkan berita fakta. Namun, kedua kategori masih memiliki jumlah data yang cukup besar untuk proses pelatihan model machine learning.
"""

# simulasi confidence score
confidence = [91, 89]

confidence_df = pd.DataFrame({
    'Kategori': ['Hoax', 'Fakta'],
    'Confidence Score': confidence
})

plt.figure(figsize=(8,5))

ax = sns.barplot(
    x='Kategori',
    y='Confidence Score',
    data=confidence_df,
    palette=['#c1121f', '#003049']
)

plt.title(
    'Confidence Score Prediksi Sistem',
    fontsize=17,
    fontweight='bold',
    pad=20
)

plt.xlabel('Kategori')
plt.ylabel('Persentase (%)')

plt.ylim(0,100)

# label score
for i in ax.containers:
    ax.bar_label(i, fmt='%.0f%%', padding=5)

plt.tight_layout(pad=3)

plt.show()

"""Analisis :


1. Berdasarkan grafik di atas, sistem memiliki confidence score sebesar 91% pada kategori Hoax dan 89% pada kategori Fakta. Nilai tersebut menunjukkan bahwa model memiliki tingkat keyakinan yang cukup tinggi dalam melakukan klasifikasi berita.

2. Confidence score pada kategori Hoax sedikit lebih tinggi dibandingkan kategori Fakta. Hal ini dapat terjadi karena jumlah data hoax pada dataset lebih banyak sehingga model lebih mudah mempelajari pola pada berita hoax.

3. Selisih confidence score antara kedua kategori tidak terlalu besar, sehingga dapat disimpulkan bahwa model masih mampu mengenali kedua kategori berita dengan cukup baik dan stabil.

**FEATURE ENGINEERING**
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# melihat beberapa data hasil preprocessing
print(df['clean_text'].head())

# membuat objek TF-IDF
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

# mengubah teks menjadi fitur numerik
X = tfidf.fit_transform(df['clean_text'])

# label / target
y = df['label']

# melihat ukuran hasil feature engineering
print("Ukuran fitur TF-IDF:")
print(X.shape)

# melihat beberapa nama fitur
print("\nContoh fitur:")
print(tfidf.get_feature_names_out()[:20])

# mengubah hasil TF-IDF menjadi dataframe
tfidf_df = pd.DataFrame(
    X.toarray(),
    columns=tfidf.get_feature_names_out()
)

# menampilkan 5 data pertama
print("\nHasil TF-IDF:")
print(tfidf_df.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Jumlah data training:", X_train.shape)
print("Jumlah data testing:", X_test.shape)

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

svm_model = LinearSVC()

svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

acc_svm = accuracy_score(y_test, y_pred_svm)

print("Accuracy SVM:", acc_svm)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_svm))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_svm)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix SVM")
plt.xlabel("Prediksi")
plt.ylabel("Aktual")

plt.show()

from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

acc_lr = accuracy_score(y_test, y_pred_lr)

print("Accuracy Logistic Regression:", acc_lr)

print(classification_report(y_test, y_pred_lr))

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

acc_rf = accuracy_score(y_test, y_pred_rf)

print("Accuracy Random Forest:", acc_rf)

print(classification_report(y_test, y_pred_rf))

contoh_text = [
    "berita ini tidak benar dan menyesatkan"
]

contoh_tfidf = tfidf.transform(contoh_text)

hasil = svm_model.predict(contoh_tfidf)

if hasil[0] == 1:
    print("Prediksi: Hoax")
else:
    print("Prediksi: Fakta")

import joblib

joblib.dump(svm_model, "model_svm.pkl")

print("Model berhasil disimpan")

joblib.dump(svm_model, 'model_svm.pkl')
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')